on:
    push:
        branches:
            - master
        paths:
            - "src/**"

name: Deploy extension
jobs:
    deploy:
        name: Release and publish
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install dependencies
              run: npm install
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              run: npx semantic-release
            - name: VSCode release plugin
              uses: lannonbr/vsce-action@master
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
              with:
                  args: publish -p $VSCE_PAT
