on:
    push:
        branches:
            - master
        paths:
            - "src/**"
            
jobs:
    test:
        name: Test
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2-beta
            - name: Install dependencies
              run: yarn
            - name: Run headless tests
              uses: GabrielBB/xvfb-action@v1.2
              with:
                  run: yarn test

    publish:
        name: Release and publish
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
            - name: Install dependencies
              run: yarn
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VSCE_TOKEN: ${{ secrets.VSCE_PAT }}
              run: yarn semantic-release
