on:
    push:
        branches:
            - master

jobs:
    test:
        name: Test
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install dependencies
              run: yarn
            - name: Run headless tests
              uses: GabrielBB/xvfb-action@v1.2
              with:
                  run: yarn test

    publish:
        name: Release and publish
        needs: test
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install dependencies
              run: npm install
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              run: npx semantic-release
            - name: VSCode release plugin
              uses: JCofman/vscodeaction@master
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
              with:
                  args: publish -p $VSCE_PAT
